# Generated by Django 4.2.5 on 2023-09-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='CustomerRecord',
        ),
    ]
